// client/src/components/CharacterSummary.vue
<script setup lang="ts">
/**
 * The identifying lines for one character: portrait, name, and the handful of
 * text attributes that say what it is.
 *
 * The same block appears twice in the Backbone app, in two templates that had
 * drifted apart only in their wrapper:
 * `templates/single-character-list-item.html` (the header of the character
 * sheet) and `templates/character-list-item.html` (a row in a list). The body
 * is identical, so it is one component here and the wrapper is the caller's.
 *
 * Which lines are shown depends on the creature type, and the three branches are
 * reproduced exactly -- including which fields share a line, which line is
 * conditional, and the fact that a Vampire is the `else`. `type` absent means
 * Vampire; see `venueOf`.
 *
 * ## The owner line, and why it is written this way
 *
 * `owner` is a pointer that is deliberately NOT `include`d by any character
 * query. Including it made parse-server delete the pointer outright for a
 * private owner, and `Character#get_me_acl` reads a missing owner as "no owner"
 * and grants the CURRENT user read and write -- so merely opening someone
 * else's sheet rewrote its ACL to the viewer.
 *
 * Without the include the pointer survives but carries no data, so
 * `owner.get('username')` is undefined and this renders nothing. That is what
 * the original did too. An ABSENT owner is a different thing entirely: it means
 * the account was deleted, and the sheet says so.
 */
import { computed } from 'vue'
import Parse from '@/parse'
import { track } from '@/parse/reactivity'
import { venueOf } from '@/parse/classes'

const props = defineProps<{
  character: Parse.Object
  /** Portrait size to request, matching the template's `get_thumbnail_sync(128)`. */
  thumbSize?: number
  /**
   * Whether the portrait is its own link to the portrait editor.
   *
   * True on the character sheet, where the whole block stands alone. False in a
   * list, where the block already sits inside the row's anchor and a nested
   * `<a>` is invalid HTML that browsers recover from unpredictably -- the
   * original's two templates differ on exactly this line.
   */
  portraitLink?: boolean
}>()

const attr = (name: string) => (track(props.character).get(name) as string | undefined) ?? ''

const venue = computed(() => venueOf(track(props.character).get('type')))

const name = computed(() => attr('name'))

const thumbnail = computed(() => {
  const c = track(props.character) as unknown as { get_thumbnail_sync?: (n: number) => string }
  return c.get_thumbnail_sync?.(props.thumbSize ?? 128)
})

/**
 * The venue-specific lines, in the order and grouping the templates used.
 * A line whose parts are all empty is dropped, which is what the `if` wrappers
 * around some of them did.
 */
const lines = computed<string[]>(() => {
  const join = (...parts: string[]) => parts.filter(Boolean).join(' ')
  const out: string[] = []

  if (venue.value === 'Werewolf') {
    if (attr('wta_tribe') || attr('wta_breed') || attr('wta_auspice')) {
      out.push(join(attr('wta_tribe'), attr('wta_breed'), attr('wta_auspice')))
    }
    out.push(join(attr('wta_faction'), attr('archetype'), attr('wta_camp')))
    out.push(attr('antecedence'))
  } else if (venue.value === 'ChangelingBetaSlice') {
    if (attr('ctdbs_kith') || attr('ctdbs_fealty_court') || attr('archetype')) {
      out.push(join(attr('ctdbs_kith'), attr('ctdbs_fealty_court'), attr('archetype')))
    }
    out.push(join(attr('ctdbs_kith_group_type'), attr('ctdbs_noble_house')))
    out.push(attr('antecedence'))
  } else {
    out.push(join(attr('sect'), attr('archetype'), attr('clan')))
    if (attr('antecedence') || attr('faction') || attr('title')) {
      out.push(join(attr('antecedence'), attr('faction'), attr('title')))
    }
  }

  /*
   * The unconditional lines above can still come out empty -- the original
   * emitted `<p>  </p>` in that case. Dropping them is the one cosmetic
   * difference here, and it removes blank rows rather than adding anything.
   */
  return out.filter((line) => line.length > 0)
})

/** `undefined` = owner present but unreadable; `null` = no owner at all. */
const ownerLine = computed<string | null | undefined>(() => {
  const c = track(props.character)
  if (!c.has('owner')) return null
  const owner = c.get('owner') as Parse.User | undefined
  const username = owner?.get('username') as string | undefined
  if (!username) return undefined
  const realname = (owner?.get('realname') as string) || ''
  const email = (owner?.get('email') as string) || ''
  return [realname, email, username].filter(Boolean).join(' ')
})
</script>

<template>
  <a v-if="thumbnail && portraitLink !== false" :href="`#character/${character.id}/portrait`">
    <img :src="thumbnail" class="character-link-portrait" alt="" />
  </a>
  <img v-else-if="thumbnail" :src="thumbnail" class="character-link-portrait" alt="" />
  <h2>{{ name }}</h2>
  <p v-for="(line, i) in lines" :key="i">{{ line }}</p>
  <p v-if="ownerLine === null">DELETED</p>
  <p v-else-if="ownerLine">{{ ownerLine }}</p>
</template>

// web/src/screens/CharacterSummary.tsx
import type { Character } from '@/parse/models/Character';

/**
 * The character's identity block, at the top of their sheet.
 *
 * Ports templates/single-character-list-item.html and views/CharacterListItem.js.
 *
 * Almost the same content as a row of the character list, with two differences
 * that matter: there is no wrapping `<li>` or row anchor -- this is not a list
 * row -- and the portrait is itself a link to the portrait page rather than
 * decoration inside a link to the sheet.
 *
 * The per-creature field blocks are the same rules as
 * screens/CharacterListItem.tsx, including the conditional lines that keep an
 * unfinished character from showing a run of blank paragraphs.
 */

function get(character: Character, key: string): string | undefined {
  const value = character.get(key) as unknown;
  return value === undefined || value === null ? undefined : String(value);
}

/** Join fields with single spaces, dropping the ones that are not set. */
function joinFields(...values: (string | undefined)[]): string {
  return values.filter((value) => value && value.trim()).join(' ');
}

function VenueLines({ character }: { character: Character }) {
  if (character.venue === 'Werewolf') {
    const tribe = get(character, 'wta_tribe');
    const breed = get(character, 'wta_breed');
    const auspice = get(character, 'wta_auspice');
    return (
      <>
        {tribe || breed || auspice ? <p>{joinFields(tribe, breed, auspice)}</p> : null}
        <p>
          {joinFields(
            get(character, 'wta_faction'),
            get(character, 'archetype'),
            get(character, 'wta_camp'),
          )}
        </p>
        <p>{get(character, 'antecedence')}</p>
      </>
    );
  }

  if (character.venue === 'ChangelingBetaSlice') {
    const kith = get(character, 'ctdbs_kith');
    const court = get(character, 'ctdbs_fealty_court');
    const archetype = get(character, 'archetype');
    return (
      <>
        {kith || court || archetype ? <p>{joinFields(kith, court, archetype)}</p> : null}
        <p>
          {joinFields(
            get(character, 'ctdbs_kith_group_type'),
            get(character, 'ctdbs_noble_house'),
          )}
        </p>
        <p>{get(character, 'antecedence')}</p>
      </>
    );
  }

  const antecedence = get(character, 'antecedence');
  const faction = get(character, 'faction');
  const title = get(character, 'title');
  return (
    <>
      <p>
        {joinFields(get(character, 'sect'), get(character, 'archetype'), get(character, 'clan'))}
      </p>
      {antecedence || faction || title ? <p>{joinFields(antecedence, faction, title)}</p> : null}
    </>
  );
}

/**
 * The owner line.
 *
 * No owner at all prints "DELETED"; an owner whose username did not resolve
 * prints nothing. That middle case is not an oversight -- the character fetch
 * deliberately does not `include("owner")` (see parse/character/load.ts for
 * why), so on a player's own sheet the pointer is a stub and this renders
 * nothing at all.
 */
function OwnerLine({ character }: { character: Character }) {
  const owner = character.owner;
  if (!owner) return <p>DELETED</p>;
  const username = owner.get('username') as string | undefined;
  if (!username) return null;
  return (
    <p>
      {joinFields(
        owner.get('realname') as string | undefined,
        owner.get('email') as string | undefined,
        username,
      )}
    </p>
  );
}

export function CharacterSummary({ character }: { character: Character }) {
  const id = character.id ?? '';
  return (
    // The wrapper carries the character's objectId as its id and "Vampire" as
    // its class, and neither was intended. `new CharacterListItem(this.model)`
    // passes the *model* where Backbone.View expects an options bag, and the
    // View constructor picks `id` and `className` off whatever it is given --
    // so a Parse.Object hands over its objectId and its className. It is in the
    // DOM today, so it is here too.
    //
    // `className` is "Vampire" for all three creature types, since they share
    // one Parse class. See models/Character.ts.
    //
    // The id here is CORRECT, and the legacy one often is not. CharacterView
    // memoises the sub-view -- `this.subview = this.subview || new
    // CharacterListItem(this.model)` (CharacterView.js:37) -- so the element is
    // built once per page load and keeps whichever character was opened first.
    // Open character A and then character B and the legacy sheet shows B's
    // content inside a div carrying A's objectId. Verified against the running
    // app: opening a werewolf after a vampire leaves the wrapper reading
    // #9cYrGGv2w3.Vampire. Everything else on all three sheets matches line for
    // line, so this is the only difference and it is not one worth copying.
    <div id={id} className={character.className}>
      <a href={`#character/${id}/portrait`}>
        <img src={character.thumbnailUrl(128)} className="character-link-portrait" alt="" />
      </a>
      <h2>{character.name}</h2>
      <VenueLines character={character} />
      <OwnerLine character={character} />
    </div>
  );
}
